[package]
name = "bayesian-bernoulli-bandits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
ordered-float = { version = "3.0.0", features = ["rand"] }
num-integer = "0.1"
