[package]
name = "bayesian-bernoulli-bandits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
num-integer = "0.1"
num-bigint = "0.4"
